### ISSUE TITLE
Darter pro keyboard backlight control broken after latest update

### ISSUE THREAD

**Issue by bwat47** [pop-os/system76-dkms#30] opened 2019-08-06 11:15 UTC
After getting the latest update to system76-dkms (1.0.5~1565016960~19.04~95bffee), the keyboard backlight hotkeys no longer work.

The backlight is stuck on (and with a blue color) no matter what

Ubuntu 19.04 
Darter pro (darp5)

The behavior is the same as this prior issue that was fixed in april: https://github.com/pop-os/system76-dkms/pull/23

**Comment by jackpot51** [comment] 2019-08-06 12:42
Thanks, I will make sure there hasn't been a regression in a couple hours

**Comment by jackpot51** [comment] 2019-08-06 12:47
It looks like the same mistake was made again - not sure why I keep thinking it has the same keyboard backlight as the Galago Pro. It will be fixed soon.

**Comment by jackpot51** [comment] 2019-08-06 14:02
It is fixed in system76-dkms 1.0.6

**Closed by jackpot51** 2019-08-06 14:02 UTC

**Comment by mebays** [comment] 2021-11-29 13:26
I normally have my backlight off, but doing an early morning start I was trying to turn mine on and then found this issue. Is this a reoccurring thing?  

Here are my specs and I am running a darter pro `darp6` 

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

system76-dkms:
  Installed: 1.0.13~1630342318~20.04~68bd479
  Candidate: 1.0.13~1630342318~20.04~68bd479
  Version table:
 *** 1.0.13~1630342318~20.04~68bd479 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by jacobgkau** [comment] 2021-11-29 16:27
> I normally have my backlight off, but doing an early morning start I was trying to turn mine on and then found this issue. Is this a reoccurring thing?

@mebays Are you using proprietary EC? You are probably experiencing https://github.com/pop-os/system76-acpi-dkms/issues/15.

You can [switch to Open EC](https://support.system76.com/articles/transition-firmware) if you don't have a reason to require proprietary EC, or watch that issue for updates.

**Comment by mebays** [comment] 2021-11-29 16:48
Using that link I'm using Open Firmware.

**Comment by jacobgkau** [comment] 2021-11-29 16:59
> Using that link I'm using Open Firmware. Went ahead and followed those directions though and looks like it's working now after reboot.

Just to clarify, Open Firmware does not imply Open EC. "Open Firmware" refers to UEFI firmware/coreboot, while "Open EC" refers to EC firmware. darp6 shipped with Open Firmware but proprietary EC. It sounds like you successfully transitioned to Open EC. Glad to hear it's working!

**Comment by nNabakhteveli** [comment] 2021-12-05 14:49
Thanks Jacob! After hours of searching, [this](https://support.system76.com/articles/transition-firmware/) worked
